### PR TITLE
Add codecamp external participants

### PR DESCRIPTION
**Pull request by bliemli**
## Config changes proposed in this pull request
- Add users phil-pona, madchr1st and myself (we are external codecamp participants, @mebagel can confirm)

### All above-mentioned users agree that

- [x] I have **read and understood the [Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/)**
- [x] I agree to **act accordingly (with due dilligence) to our guidelines**
- [x] I have **no open questions** regarding the topics covered (please delete the "open questions" section)

### CODE REVIEW

**Review by kullmanp — CHANGES_REQUESTED** [review]
You should probably add code camp participants to the baloise incubator org: https://github.com/baloise-incubator/org

**Comment by culmat** [comment]
> You should probably add code camp participants to the baloise incubator org: https://github.com/baloise-incubator/org

IMHO baloise org can and should be used. baloise-incubator is specific to the incubator cluster. If you need that, you can also request org memebership there.

**Review by culmat — APPROVED** [review]
Welcome and enjoy the code camp :-)

**Comment by culmat** [comment]
After chat with Peter, I've merged this

**Comment by bliemli** [comment]
Thank you!

**Pull request merged**
