### PR TITLE
add aMiladinovic as a member

### PR DESCRIPTION
**Pull request by hirsch88**
## Config changes proposed in this pull request
- 
- 

### I acknowledge that
- [x] I have **read and understood the [Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/)**
- [x] I agree to **act accordingly (with due dilligence) to our guidelines**
- [x] I have **no open questions** regarding the topics covered (please delete the "open questions" section)

### Open questions
- 
-

### CODE REVIEW

**Review by kullmanp — APPROVED** [review]

**Comment by MarkusTiede** [comment]
@hirsch88 - make sure to use your Baloise eMail Identity for proposals here.

**Comment by MarkusTiede** [comment]
And if you're filing this in respect for a third person: please make sure that the 3rd person is actually stating the details above.

**Review by MarkusTiede — CHANGES_REQUESTED** [review]
- [ ] correct proposer eMail identity
- [ ] make sure proposed person is actually checking / commenting the information on his own behalf

**Comment by hirsch88** [comment]
will create a new one :-)

**Pull request closed without merging**
